version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Building Vite React app..."
      - npm run build

  post_build:
    commands:
      - echo "Build finished at $(date)"

artifacts:
  base-directory: dist
  files:
    - '**/*'
